import type { ForgePrd, PrdGeneration } from "./types.js";

function bullets(items: string[]): string {
  return items.length > 0 ? items.map((item) => `- ${item}`).join("\n") : "- None";
}

function renderPrdBody(prd: ForgePrd): string {
  const sections: string[] = [
    `# ${prd.title}`,
    "",
    "## Problem",
    "",
    prd.problem,
    "",
    "## Solution",
    "",
    prd.solution,
    "",
    "## Goals",
    "",
    bullets(prd.goals),
    "",
    "## Non-goals",
    "",
    bullets(prd.nonGoals),
    "",
    "## User stories",
    "",
    ...(prd.userStories.length > 0
      ? prd.userStories.map((story, index) => `${index + 1}. **${story.id}** — As ${story.actor}, I want ${story.capability}, so that ${story.benefit}.`)
      : ["None"]),
    "",
    "## Acceptance criteria",
    "",
    ...prd.acceptance.flatMap((criterion) => [
      `- [ ] **${criterion.id}** — ${criterion.statement}`,
      `  - Verification: ${criterion.verification.join("; ")}`,
    ]),
    "",
    "## Behavior",
    "",
    "### Happy path",
    "",
    bullets(prd.behavior.happyPath),
    "",
    "### Error paths",
    "",
    bullets(prd.behavior.errorPaths),
    "",
    "### Edge cases",
    "",
    bullets(prd.behavior.edgeCases),
    "",
    "## Design decisions",
    "",
    ...(prd.decisions.length > 0
      ? prd.decisions.flatMap((decision) => [
          `### ${decision.id}`,
          "",
          decision.decision,
          "",
          `**Rationale:** ${decision.rationale}`,
          "",
          `**Evidence:** ${decision.evidenceIds.join(", ") || "None"}`,
          ...(decision.alternatives?.length ? ["", `**Rejected alternatives:** ${decision.alternatives.join("; ")}`] : []),
          "",
        ])
      : ["None", ""]),
    "## Impact evidence",
    "",
    ...prd.impactEvidence.map((evidence) => `- **${evidence.id}** — \`${evidence.path}#${evidence.symbol}\`: ${evidence.claim} (${evidence.repositoryRevision})`),
    "",
    "## Testing decisions",
    "",
    ...(prd.testSeams.length > 0
      ? prd.testSeams.map((seam) => `- **${seam.name}** (${seam.level}) — ${seam.verification}; evidence: ${seam.evidenceIds.join(", ") || "None"}`)
      : ["None"]),
    "",
    "## Risks",
    "",
    ...(prd.risks.length > 0
      ? prd.risks.map((risk) => `- **${risk.risk}** — ${risk.mitigation}`)
      : ["None"]),
    "",
    "## Delivery plan",
    "",
    ...prd.deliveryBoundaries.flatMap((boundary) => [
      `### ${boundary.id}: ${boundary.title}`,
      "",
      `**Outcome:** ${boundary.outcome}`,
      "",
      `**Goal:** ${boundary.goal}`,
      "",
      "**Scope:**",
      "",
      bullets(boundary.scope),
      "",
      `**Acceptance:** ${boundary.acceptanceIds.join(", ")}`,
      "",
      `**Independently deliverable:** ${boundary.independentlyDeliverable ? "Yes" : "No"}`,
      "",
      `**Dependencies:** ${boundary.dependencies.join(", ") || "None"}`,
      "",
      `**Rationale:** ${boundary.rationale}`,
      "",
    ]),
  ];

  if (prd.migration) sections.push("", "## Migration", "", prd.migration);
  if (prd.rollback) sections.push("", "## Rollback", "", prd.rollback);
  if (prd.diagrams.length > 0) {
    sections.push("", "## Diagrams", "");
    for (const diagram of prd.diagrams) {
      sections.push(
        `### ${diagram.title}`,
        "",
        diagram.rationale,
        "",
        "```mermaid",
        diagram.mermaid,
        "```",
        "",
      );
    }
  }
  sections.push("", "## Open questions", "", bullets(prd.openQuestions), "");
  return sections.join("\n");
}

export function renderPrd(generation: PrdGeneration): string {
  return [
    "<!-- Generated by pi-forge-workflow. Edit the structured PRD through Forge Runtime. -->",
    `<!-- Work Item: ${generation.workItemId}; Generation: ${generation.generation}; Hash: ${generation.contentHash} -->`,
    "",
    renderPrdBody(generation.prd),
  ].join("\n");
}
